GestHot/GestHot/Models/Comment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestHot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {

        public Comment() { }
        public Comment(int idU, int idH, string message)
        {
            
            this.message = message;
            this.idU = idU;
            this.idH = idH;
        }

        public int idC { get; set; }
        public string message { get; set; }
        public int idU { get; set; }
        public int idH { get; set; }
        public Nullable<int> prediction { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual User User { get; set; }
    }
}

GestHot/GestHot/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestHot.Models;
using Microsoft.Ajax.Utilities;

namespace GestHot.Controllers
{
    public class OwnerController : Controller
    {
        private GestHotEntities1 db = new GestHotEntities1();

        // GET: Owner
        public ActionResult Index(int?id)
        {
            //return View(hotelNote(id));
            hotelNote();
            return View(db.Hotels.Where(e => e.idU== id));
        }

        public void hotelNote()
        {
            db.Hotels.ForEach(hot => {
                int good = hot.Comments.Where(e => e.prediction == 1).Count();
                int neutral = hot.Comments.Where(e => e.prediction == 0).Count();
                int bad = hot.Comments.Where(e => e.prediction == -1).Count();
                int all = good + bad + neutral;
                int res;
                if (all == 0) { res = 0; }
                else
                {
                    res = (good * 100) / all;
                }
                if (res == 0)
                {
                    hot.note = 0;
                }
                if (res == 100)
                {
                    hot.note = 5;
                }
                if (res > 0 && res < 25)
                {
                    hot.note = 1;
                }
                else if (res >= 25 && res < 50)
                {
                    hot.note = 2;
                }
                else if (res >= 50 && res < 75)
                {
                    hot.note = 3;
                }
                else if (res >= 75 && res < 100)
                {
                    hot.note = 4;
                }
                
            });db.SaveChanges();
        }

        

        // GET: Owner/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Owner/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idU,Name,LastName,Email,Password,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = Session["userId"].ToString() });
            }

            return View(user);
        }

        


        //See Comments
        public ActionResult Comments(int? id)
        {
            var hotel = db.Hotels.Find(id);
            if(hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel.Comments);
        }

        //Edit hotel
        //Get
        public ActionResult Edit(int? id)
        {
            var hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idH,name,adresse,description,nbCH,note,prix,idU")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                
                hotel.idU = int.Parse((string)Session["userID"]);
                db.Entry(hotel).State = EntityState.Modified;
                db.SaveChanges();
                TempData["hotel"] = "Hotel edited successfully";
                return RedirectToAction("Index", new { id = Session["userId"].ToString() });
            }
            return View(hotel);
        }

        //new Hotel

        //Get 
        public ActionResult newHotel()
        {
            
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult newHotel([Bind(Include = "name,adresse,description,nbCH,note,idU,fileH,prix")] Hotel hotel, HttpPostedFileBase fileH)
        {
            if (ModelState.IsValid)
            {
                hotel.idU = int.Parse((string)Session["userID"]);
                //hotel.note = 0;
                if (db.Hotels.FirstOrDefault(e => e.name.Equals(hotel.name) && e.adresse.Equals(hotel.adresse)) != null)
                {
                    TempData["hotel"] = "This hotel already exists";
                    return RedirectToAction("Index", new { id = Session["userId"].ToString() });
                }
                else
                {

                    string path = Path.Combine(Server.MapPath("~/UploadedFiles"), Path.GetFileName(fileH.FileName));
                    fileH.SaveAs(path);
                    hotel.fileH = "/UploadedFiles/" + fileH.FileName;
                    db.Hotels.Add(hotel);
                    db.SaveChanges();
                    TempData["hotel"] = "Hotel created successfully";
                    return RedirectToAction("Index", new { id = Session["userId"].ToString() });
                }
            }
            return HttpNotFound();
        }

        //See details
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel= db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
            
        }
        public ActionResult Delete(int? id)
        {
            Hotel hotel = db.Hotels.Find(id);
            var cmt = db.Comments.Where(e => e.idH == id);
            var favs = db.Favorites.Where(e => e.idH == id);
            var rese = db.Reservations.Where(e => e.idH == id);
            foreach( var cm in cmt)
            {
                db.Comments.Remove(cm);
            }
            foreach (var fav in favs)
            {
                db.Favorites.Remove(fav);
            }
            foreach (var fav in rese)
            {
                db.Reservations.Remove(fav);
            }
            db.Hotels.Remove(hotel);

            db.SaveChanges();
            return RedirectToAction("Index", new {id = Session["userId"].ToString() });
        }
    }
}

GestHot/GestHot/Views/Owner/Comments.cshtml
@model IEnumerable<GestHot.Models.Comment>

@{
    ViewBag.Title = "Comments";
}

<div class="container">
    <div class="row my-5">
        <h2 class="text-red">Comments</h2>
    </div>
    <div class="my-3 row">
        <table class="table table-striped">
            <tr>
                <th class="text-center">
                    <h4>Comment</h4>
                </th>
                <th class="text-center">
                    <h4>User Name</h4>
                </th>
                <th class="text-center">
                    <h4>Comment prediction</h4>
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.message)
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.User.Name)
                    </td>
                    <td class="text-center">
                        @if (item.prediction == 1)
                        {
                            <i class="bi bi-emoji-smile-fill"></i>
                        }
                        else if (item.prediction == -1)
                        {
                            <i class="bi bi-emoji-frown-fill"></i>
                        }
                        else
                        {
                            <i class="bi bi-emoji-neutral-fill"></i>
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

GestHot/GestHot/Views/Owner/Details.cshtml
@model GestHot.Models.Hotel

@{
    ViewBag.Title = "Details";
}


<div class="container">
    <div class="row my-5">
        <h2 class="text-red">Details</h2>
    </div>
    <div class="card">
        <div class="card-header">
            <h4 class="text-red">@Html.DisplayFor(model => model.name)</h4>
        </div>
        <div class="card-body">
            <div class="row">
                <img src="@Html.DisplayFor(model => model.fileH)" class="img-thumbnail"/>
            </div>
            <div class="row">
                <div class="row">
                    <div class="col-sm-8">
                        <h4>@Html.DisplayNameFor(model => model.name)</h4>
                        <p>@Html.DisplayFor(model => model.name)</p>
                    </div>
                    <div class="col-sm-8">
                        <h4>@Html.DisplayNameFor(model => model.adresse)</h4>
                        <p>@Html.DisplayFor(model => model.adresse)</p>
                    </div>
                </div>
                <div class="row">
                    <h4>@Html.DisplayNameFor(model => model.description)</h4>
                    <p>@Html.DisplayFor(model => model.description)</p>
                </div>
                <div class="row">
                    <div class="col-sm-8">
                        <h4>Number of rooms</h4>
                        <p>@Html.DisplayFor(model => model.nbCH)</p>
                    </div>
                    <div class="col-sm-8">
                        <h4>@Html.DisplayNameFor(model => model.note)</h4>
                        <p>@Html.DisplayFor(model => model.note)</p>
                    </div>
                    <div class="col-sm-8">
                        <h4>Price</h4>
                        <p>@Html.DisplayFor(model => model.prix) $</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GestHot/GestHot/Views/Owner/Edit.cshtml
@model GestHot.Models.Hotel

@{
    ViewBag.Title = "Edit";
}


<div class="container">
    <div class="row my-5">
        <h2 class="text-red">Edit</h2>
    </div>
    <div class="row my-3">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.idH)
            @Html.HiddenFor(model => model.note)
            <div class="row">
                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Name</label>
                        @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Adresse</label>
                        @Html.EditorFor(model => model.adresse, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="mb-3">
                        <label class="form-label">Description</label>
                        @Html.TextAreaFor(model => model.description,  new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Price</label>
                        @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Number of rooms</label>
                        @Html.EditorFor(model => model.nbCH, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

            </div>
            
            <button type="submit" class="btn btn-primary">Submit</button>
        }

    </div>
</div>

GestHot/GestHot/Views/Owner/Index.cshtml
@model IEnumerable<GestHot.Models.Hotel>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    @if (TempData["hotel"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show my-3 text-center" role="alert">
            <i class="bi bi-exclamation-diamond-fill"></i> @TempData["hotel"]
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    <div class="row my-5">
        <div class="col-sm-8">
            <h2 class="text-red">My Hotels</h2>
        </div>
        <div class="col-sm-4">
            @Html.ActionLink("New Hotel", "newHotel", null, new { @class = "btn btn-red" })
        </div>
    </div>
    <div class="row my-3">
        <table class="table table-striped">
            <tr>
                <th>
                    <h4>Name</h4>
                </th>
                <th>
                    <h4>Adresse</h4>
                </th>
                <th>
                    <h4>Rooms</h4>
                </th>
                <th>
                    <h4>Price</h4>
                </th>
                <th>
                    <h4>Note</h4>
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.adresse)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.nbCH)
                    </td>
                    <td>@Html.DisplayFor(modelItem => item.prix)</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.note)
                    </td>
                    <td>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="See comments" class="mx-2 no-color" href="@Url.Action("Comments", "Owner", new { id = item.idH})"><i class="bi bi-chat-left-dots-fill"></i></a>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Edit" class="mx-2 no-color" href="@Url.Action("Edit","Owner",new { id = item.idH })"><i class="bi bi-pencil-fill"></i></a>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="See Details" class="mx-2 no-color" " href="@Url.Action("Details","Owner",new { id = item.idH })"><i class="bi bi-file-earmark-text-fill"></i></a>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Delete" class="mx-2 no-color" " href="@Url.Action("Delete","Owner",new { id = item.idH })"><i class="bi bi-trash3-fill"></i></a>

                    </td>
                </tr>
            }

        </table>
    </div>
</div>

GestHot/GestHot/Views/Owner/newHotel.cshtml
@model GestHot.Models.Hotel

@{
    ViewBag.Title = "newHotel";
}
<div class="container">
    <div class="row my-4">
        <h2 class="text-center text-red text-uppercase">Hotel</h2>
    </div>
    <div class="row">
        @using (Html.BeginForm("newHotel", "Owner", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.HiddenFor(model => model.idU, new { id = 1 })
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group my-3">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group my-3">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.adresse, new { htmlAttributes = new { @class = "form-control", @placeholder = "Adresse" } })
                    @Html.ValidationMessageFor(model => model.adresse, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group my-3">
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.description, new { @class = "form-control", @placeholder = "Description" })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group my-3">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nbCH, new { htmlAttributes = new { @class = "form-control", @placeholder = "Number of rooms" } })
                    @Html.ValidationMessageFor(model => model.nbCH, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group my-3">
                <div class="col-md-10">
                    @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control", @placeholder = "Price" } })
                    @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group my-3">
                @Html.LabelFor(model => model.fileH, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fileH, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                    @Html.ValidationMessageFor(model => model.fileH, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group my-3">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-red" />
                </div>
            </div>
        </div>
        }
    </div>
</div>